RET-1196 Create separate userfs and systemfs filesystems
Opentrons/meta-opentrons pull request #58
Opened 2022-08-26 15:29 UTC by vegano1

[RET-1196](https://opentrons.atlassian.net/browse/RET-1196)

Overview:
Update the opentrons-image-ot3 recipe to create two filesystems, a systemfs and a userfs
The systemfs contains the original rootfs tree without home/ var/, this will later on become read-only
The userfs contain the home/ and var/ directories and will be mounted on a separate partition

2022-08-26 15:34 UTC, DerekMaggio commented
How come we want separate filesystems?

2022-08-26 15:44 UTC, vegano1 commented
> Noob question, how come we want separate filesystems?

We want to have a read-only partition (systemfs) for our own software and a read-write partition (userfs) for user data. The idea is that 
1. it will be safer to lock the parts of the system we don't want users to mess with
2. it will make it easier to do a factory reset since all the user data will be in a separate partition.

2022-08-29 15:16 UTC, sfoster1 requested changes
Looks good overall but we should do a pass and make sure we don't have duplications between the machine config and the image recipe

2022-08-29 15:16 UTC, sfoster1 commented on recipes-images/images/opentrons-ot3-image.bb
> +    rsync -a ${IMAGE_ROOTFS}/ ${SYSTEMFS_DIR} --exclude 'home/' --exclude 'var/' --delete-excluded
love the use of rsync

2022-08-29 19:24 UTC, vegano1 commented on recipes-images/images/opentrons-ot3-image.bb
> +add_rootfs_version () {
ya will add this in a separate pr that deals with just the contents of ot3-system.zip, including the VERSION.json file, etc

2022-08-29 21:17 UTC, sfoster1 approved these changes
Nice, looks good to me!

So after this, we should get both filesystems in the tezi image?

2022-08-29 22:08 UTC, vegano1 commented
> Nice, looks good to me!
> 
> So after this, we should get both filesystems in the tezi image?

next pr will, this was prep work to generate the filesystems which tezi uses.

2022-08-29 22:09 UTC, merged