RET-1172 create bootable tezi image + opentrons update
Opentrons/meta-opentrons pull request #62
Opened 2022-09-15 16:09 UTC by vegano1

Overview:
These changes produce a bootable Tezi image for flashing as well as the updatable image used for the opentrons app. Note the rootfs is mounted as read-write for now, so we can move along with Opentrons updates.

Changes:
- Remove custom image_type_tezi_ot3.bbclass and integrate tezi image generation into our own opentrons-ot3-image recipe
- Separate the rootfs into a systemfs for system applications (robot-server, update-server, etc) and systemfs for user level changes.
- Create a modified image.json file for the Tezi image that creates two partitions for our A/B update mechanism
- Use the generated Tezi image fragments to build our own Tezi tarball with our generated systemfs and userfs
- Create a VERSION.json file to be used for updates via the Opentrons app
- Create the ot3-system.zip with VERSION.json systemfs.ext, systemfs 256 hash
- Remove wks file

2022-09-15 16:33 UTC, sfoster1 requested changes
Looks almost great, we need to fix up the partition allocation and then we're solid I think.

We're not currently mounting the userfs, right?

2022-09-15 16:33 UTC, sfoster1 commented on recipes-images/images/opentrons-ot3-image.bb
> +    ot3_partitions = [{
This doesn't quite look right. We want
- boot, FATFS, 48 meg
- RFS1, holding systemfs, fixed size (here, 3072M; would be good to cut this down if we can)
- RFS2, holding systemfs, same size as RFS1
- VARFS or whatever, holding userfs, remaining space on the storage

Right now, we've got bootfs and RFS1, but the volume labeled REFS2 has the userfs, and there's no dedicated partition for it.

Having two dedicated rootfs partitions allows us to update the partition we're not booted from.

2022-09-16 15:27 UTC, sfoster1 approved these changes
This looks really good to me now! I still need to build an image and mount and poke around in some root filesystems to be sure but I think this is great.

2022-09-22 13:21 UTC, sfoster1 approved these changes
Excellent, looks good to me!

My only quibble is that 2 gigs is pretty darn big for the rootfs, it'll make updates very slow - even if the filesystems compress well, they still have to be written. Do you have an idea of how much space is actually used in them?

2022-09-22 19:17 UTC, vegano1 commented
> Excellent, looks good to me!
> 
> My only quibble is that 2 gigs is pretty darn big for the rootfs, it'll make updates very slow - even if the filesystems compress well, they still have to be written. Do you have an idea of how much space is actually used in them?

Currently, we are using ~900mb, I've reduced the rootfs partition size from 2GB to 1.5GB. 
We can adjust as needed, don't want to bring it too low so we don't run into the same issue as OT2. 
That being said we will be doing some trimming in the near future and can adjust as needed.

2022-09-22 21:16 UTC, merged